### ISSUE TITLE
教程能否再详细点

### ISSUE THREAD

**Issue by kkkooo999** [Li3Zi3han2/UmateDownload#1]
如何编译，如何使用，如何运行

**Comment by Li3Zi3han2** [comment]
安装Mathematica就能用了
安装教程：https://tiebamma.github.io/InstallTutorial/

**Comment by kkkooo999** [comment]
提示：Syntax::sntxf: "Um" 后面不能跟着 "ateDownload[url_String/;StringMatchQ[url,"https://umate.me/personInfo/"~~__],dir_String,"圈子",{n1_Integer,n2_Integer}/;1<=n1<=n2]:=Module[".
Syntax::sntxf: "" 后面不能跟着 "TPRequest[url,<|"Headers"->header|>],name];".
Syntax::sntxf: "" 后面不能跟着 "(*清除定义*)".
我已经获取到URL为："https://api.umate.me/api/circle/circle_post_list?page=1&media_type=-1&circle_slug=QdEZDb&username=DDlalalo" ^
  -H "accept: application/json" ^
  -H "accept-language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6" ^
  -H "authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS51bWF0ZS5tZS9hcGkvY2lyY2xlL2NpcmNsZV9tZWRpYV9saXN0IiwiaWF0IjoxNzIxMjI0MzEyLCJleHAiOjE3MjM4MTYzMTIsIm5iZiI6MTcyMTIyNDMxMiwianRpIjoidEV0SXE3SVRZVnJCNDJDViIsInN1YiI6IjI5Nzc1OCIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Gn92IaBU7MjOTEg6vhmqbWiGnPImqyIfMzeZVAInOI0" ^
  -H "lang: zhCN" ^
  -H "origin: https://umate.me" ^
  -H "platform: pc" ^
  -H "priority: u=1, i" ^
  -H "referer: https://umate.me/" ^
  -H ^"sec-ch-ua: ^\^"Not/A)Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"126^\^", ^\^"Microsoft Edge^\^";v=^\^"126^\^"^" ^
  -H "sec-ch-ua-mobile: ?0" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^" ^
  -H "sec-fetch-dest: empty" ^
  -H "sec-fetch-mode: cors" ^
  -H "sec-fetch-site: same-site" ^
  -H "time-zone: UTC+08:00" ^
  -H "timezone: Asia/Shanghai" ^
  -H "user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0""~~__]
不清楚应该怎么使用

**Comment by kkkooo999** [comment]
提示：Syntax::sntxf: "Um" 后面不能跟着 "ateDownload[url_String/;StringMatchQ[url,"https://umate.me/personInfo/"__],dir_String,"圈子",{n1_Integer,n2_Integer}/;1<=n1<=n2]:=Module[".
Syntax::sntxf: "" 后面不能跟着 "TPRequest[url,<|"Headers"->header|>],name];".
Syntax::sntxf: "" 后面不能跟着 "(清除定义)".
我已经获取到URL为："https://api.umate.me/api/circle/circle_post_list?▮▮▮▮▮▮"
不清楚应该怎么使用

**Comment by Li3Zi3han2** [comment]
修了个小bug之后发现下载出错，等我更新吧。

**Comment by kkkooo999** [comment]
感谢回复，期待更新

**Comment by Li3Zi3han2** [comment]
已更新，如有其他bug请另开issue。

**Comment by WSimonn** [comment]
是必须要先购买视频，才能下载已经购买的是视频，不能够直接获取未购买的吗
