### ISSUE TITLE
大佬。能否出一个更详细一点的教程示例？

### ISSUE THREAD

**Issue by KOK129303** [Li3Zi3han2/UmateDownload#2]
或者更简单一点，比如：of那样。js文本里放入cookie就能下载使用

**Comment by Li3Zi3han2** [comment]
我是真的菜，不会其他编程语言啊……等修好了信得过我可以代下。

**Comment by KOK129303** [comment]
> 我是真的菜，不会其他编程语言啊……等修好了信得过我可以代下。
![image](https://github.com/user-attachments/assets/8324ff5b-38f9-41bf-9038-f88316aec046)

说实话，这个网站你是第一个出下载程序的，实在不行  出个导入教程也行  拍个视频  哈哈   ，我号里还有几百刀，没法找代下啊

**Comment by Li3Zi3han2** [comment]
已更新，教程凑合看吧。
