### ISSUE TITLE
新版本的报错

### ISSUE THREAD

**Issue by kkkooo999** [Li3Zi3han2/UmateDownload#3]
新版本的报错；
StringCases::strse: StringCases[ImportTextFromURL[Missing[PartInvalid,medium],{authorization->Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS51bWF0ZS5tZS9hcGkvY2lyY2xlL2NpcmNsZV9tZWRpYV9saXN0IiwiaWF0IjoxNzIxMjI0MzEyLCJleHAiOjE3MjM4MTYzMTIsIm5i\[Ellipsis] IyNDMxMiwianRpIjoidEV0SXE3SVRZVnJCNDJDViIsInN1YiI6IjI5Nzc1OCIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Gn92IaBU7MjOTEg6vhmqbWiGnPImqyIfMzeZVAInOI0}],<<1>>:><<1>>] 的位置 1 处应该是字符串或者由字符串组成的列表.
StringCases::strse: StringCases[ImportTextFromURL[ImportTextFromURL[Missing[PartInvalid,medium],{authorization->Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS51bWF0ZS5tZS9hcGkvY2lyY2xlL2NpcmNsZV9tZWRpYV9saXN0IiwiaWF0IjoxNzIxMjI0MzEyLCJleHAiOjE3MjM4M\[Ellipsis] nRpIjoidEV0SXE3SVRZVnJCNDJDViIsInN1YiI6IjI5Nzc1OCIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Gn92IaBU7MjOTEg6vhmqbWiGnPImqyIfMzeZVAInOI0}],{<<1>>}],<<1>>] 的位置 1 处应该是字符串或者由字符串组成的列表.
StringCases::strse: StringCases[ImportTextFromURL[Missing[PartInvalid,medium],{authorization->Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwczovL2FwaS51bWF0ZS5tZS9hcGkvY2lyY2xlL2NpcmNsZV9tZWRpYV9saXN0IiwiaWF0IjoxNzIxMjI0MzEyLCJleHAiOjE3MjM4MTYzMTIsIm5i\[Ellipsis] IyNDMxMiwianRpIjoidEV0SXE3SVRZVnJCNDJDViIsInN1YiI6IjI5Nzc1OCIsInBydiI6IjIzYmQ1Yzg5NDlmNjAwYWRiMzllNzAxYzQwMDg3MmRiN2E1OTc2ZjcifQ.Gn92IaBU7MjOTEg6vhmqbWiGnPImqyIfMzeZVAInOI0}],<<1>>:><<1>>] 的位置 1 处应该是字符串或者由字符串组成的列表.
General::stop: 在本次计算中，StringCases::strse 的进一步输出将被抑制.

**Comment by Li3Zi3han2** [comment]
我下载自己的订阅没问题。你的header比我的多几个字符，不会是没订阅吧？想想就知道白嫖不了的。
